### ISSUE TITLE
yarn build is broken

### ISSUE THREAD

**Issue by JanOwiesniak** [horizon-ui/horizon-tailwind-react-nextjs#2]
I'm using the PRO Version. Running `yarn install` and `yarn build` results in multiple errors which leads to a undeployable product.

**1. Linting Issues**

```
$ next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
 ✓ Creating an optimized production build    
 ✓ Compiled successfully

Failed to compile.

./src/components/card/CardMenu.tsx
37:7  Error: Do not pass children as props. Instead, nest children between the opening and closing tags.  react/no-children-prop

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can be hotfixed by excluding `./src/components/card/CardMenu.tsx` from the linting process. Real fix is mentioned in the Error message.

**2. Naming Issues**

```
$ next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./src/components/admin/dashboards/default/YourCard.tsx:2:24
Type error: Already included file name '/myproject/src/components/card/MasterCard.tsx' differs from file name '/myproject/src/components/card/Mastercard.tsx' only in casing.
  The file is in the program because:
    Imported via "components/card/MasterCard" from file '/myproject/src/components/admin/dashboards/default/YourCard.tsx'
    Imported via 'components/card/MasterCard' from file '/myproject/src/components/admin/main/account/billing/YourCard.tsx'
    Root file specified for compilation

  1 | import Card from "components/card";
> 2 | import MasterCard from "components/card/MasterCard";
    |                        ^
  3 | import Transaction from "components/dataDisplay/Transaction";
  4 | import React from "react";
  5 | import { AiOutlinePlus } from "react-icons/ai";
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can be fixed by renaming `components/card/Mastercard.tsx` to `components/card/MasterCard.tsx`

**3. Missing Dependencies**

```
$ next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./src/components/admin/main/profile/settings/Delete.tsx:9:8
Type error: Cannot find module '@chakra-ui/react' or its corresponding type declarations.

   7 |   Text,
   8 |   useColorModeValue,
>  9 | } from '@chakra-ui/react';
     |        ^
  10 | import Card from 'components/card/Card';
  11 | 
  12 | export default function Settings() {
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Can be fixed by running `yarn add @chakra-ui/react`. Why is chakra part of this repo when we are using Tailwind?

**4. Broken References**

```
$ next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./src/components/admin/main/profile/settings/Delete.tsx:10:18
Type error: Cannot find module 'components/card/Card' or its corresponding type declarations.

   8 |   useColorModeValue,
   9 | } from '@chakra-ui/react';
> 10 | import Card from 'components/card/Card';
     |                  ^
  11 | 
  12 | export default function Settings() {
  13 |   // Chakra Color Mode
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Changing `import Card from 'components/card/Card';` to `'components/card';` inside `./src/components/admin/main/profile/settings/Delete.tsx` fixed the issue because `Card` component is defined in `components/card/index.tsx`.

**5. ReferenceError: window is not defined**

```
$ next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'appDir' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ App router is available by default now, `experimental.appDir` option can be safely removed.
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/49)  [    ]ReferenceError: window is not defined
...
 ✓ Generating static pages (49/49) 

> Export encountered errors on following paths:
        /admin/dashboards/car-interface/page: /admin/dashboards/car-interface
        /admin/dashboards/default/page: /admin/dashboards/default
        /admin/dashboards/smart-home/page: /admin/dashboards/smart-home
        /admin/main/account/all-courses/page: /admin/main/account/all-courses
        /admin/main/account/billing/page: /admin/main/account/billing
        /admin/main/applications/calendar/page: /admin/main/applications/calendar
        /admin/main/users/users-reports/page: /admin/main/users/users-reports
        /auth/forgot-password/centered/page: /auth/forgot-password/centered
        /auth/lock/centered/page: /auth/lock/centered
        /auth/sign-in/centered/page: /auth/sign-in/centered
        /auth/sign-up/centered/page: /auth/sign-up/centered
        /auth/verification/centered/page: /auth/verification/centered
        /rtl/dashboards/rtl/page: /rtl/dashboards/rtl
```

Fixing this seems to be a [bigger rewrite](https://stackoverflow.com/a/75692565).

**Comment by simmmpleweb** [comment]
Hello, @JanOwiesniak ! The Chakra component got into the archive by mistake 😅
As for the other issues :
-Linting issue fixed
-ApexCharts uses `window` for their charts, the problem was solved by dynamic importing the base chart components

Regards, Vlad.

**Comment by JanOwiesniak** [comment]
Thanks for fixing those issues. You forgot to rename `components/card/Mastercard.tsx` to `components/card/MasterCard.tsx` as mentioned above.
